### PR TITLE
refs #7388 - make foreman-selinux-enable upgrade-safe

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by lzap** [comment]
Nice, have you come up with this yourself?

**Comment by domcleal** [comment]
It's all my own work, if that's what you mean? :)

**Comment by lzap** [comment]
Good, I was trying to come up with something clever the other day to keep one transaction. Will test today.

**Comment by lzap** [comment]
I have tested this already. Do I understand the packaging PR correctly (that this was included)?

**Comment by lzap** [comment]
Merged as 2f345de, thanks Dom!

**Comment by domcleal** [comment]
The packaging PR scratch builds had this commit in, yep.  Thanks!

**Pull request closed without merging**
