### PR TITLE
Fixes #9106 - added rule for AMQP connection

### PR DESCRIPTION
**Pull request by lzap**

### CODE REVIEW

**Comment by lzap** [comment]
This conversation was moved to katello-selinux repo. Please review there.

**Comment by lzap** [comment]
Since Foreman Tasks is generic plugin, I am tempted to keep it in the foreman-selinux policy. Opinions?

**Comment by lzap** [comment]
Yeah let's keep it here as there are plans to use it for orchestration in the future.

**Comment by lzap** [comment]
@iNecas please review here. I've heard that katello-jobs is no longer an option, should we remove it from `foreman.fc` then? Any other changes to the plugin?

**Comment by domcleal** [comment]
Isn't this Katello-specific rather than foreman-tasks specific?  i.e. it's connecting to Katello/Pulp's AMPQ service from a Katello task?

**Comment by iNecas** [comment]
Yes, katello is the one to add the connection to the amqp server

**Comment by iNecas** [comment]
And yes, katello-jobs is no longer in use, we can remove those

**Comment by lzap** [comment]
I've moved the rule into foreman-tasks section and corrected the comment. @iNecas can you confirm that those are still necessary:

```
# Foreman Tasks plugin

/usr/share/gems/gems/foreman-tasks-.*/bin/foreman-tasks -- gen_context(system_u:object_r:foreman_tasks_exec_t,s0)
/opt/rh/ruby193/root/usr/share/gems/gems/foreman-tasks-.*/bin/foreman-tasks -- gen_context(system_u:object_r:foreman_tasks_exec_t,s0)
```

Thanks

**Comment by domcleal** [comment]
I think according to @iNecas' comment, that this should be in the Katello SELinux policy, not foreman-tasks.

**Comment by lzap** [comment]
@iNecas please confirm, then I will move this to Katello.

**Comment by iNecas** [comment]
I hereby confirm that this should go to the katello's selinux policy

**Comment by lzap** [comment]
Hehe, roger wilco!

**Pull request closed without merging**
