### PR TITLE
fixes #6360 - enable pulp_manage_puppet when possible

### PR DESCRIPTION
**Pull request by lzap**

### CODE REVIEW

**Comment by lzap** [comment]
The relevant pulp patch is here: https://github.com/pulp/pulp/pull/1020

**Comment by domcleal** [comment]
This is configuration of policy, so shouldn't be here, put it in the Katello installer or something.

**Comment by lzap** [comment]
Right.

**Comment by lzap** [comment]
https://github.com/Katello/puppet-pulp/pull/20

**Pull request closed without merging**
