### PR TITLE
Fixes #17460 - added puppet4 node.rb context

### PR DESCRIPTION
**Pull request by lzap**

### CODE REVIEW

**Comment by domcleal** [comment]
master is currently failing to build, please look at #64 (and rebase if necessary) before I can review this.

**Comment by lzap** [comment]
Rebased, I haven't verified if this was the only change in P4, but this is the report I am trying to fix for now.

**Comment by domcleal** [comment]
The context seems to remain at `etc_t`, did it work for you?

<pre>
# ll -Z /etc/puppetlabs/puppet/node.rb 
-r-xr-x---. puppet puppet system_u:object_r:etc_t:s0       /etc/puppetlabs/puppet/node.rb
# restorecon -Rvvn /etc/puppetlabs/puppet/node.rb                                                                    
# semanage fcontext -l | grep node.rb
/etc(/puppetlabs)?/puppet/node.rb                  all files          system_u:object_r:foreman_enc_t:s0 
</pre>

**Comment by lzap** [comment]
Did you test from RPM or custom build? I forgot to change the relabel script, fixed.

**Comment by domcleal** [comment]
That was using an RPM, but I don't see why it'd make a difference. My paste wasn't clear - even after using `restorecon`, the context was unchanged. The issue is more with the policy.

**Comment by lzap** [comment]
Hmm the regexp might be bad, also not changing for me. Lemme rewrite it.

**Comment by lzap** [comment]
This is crazy, I just loaded the policy, doublechecked the pp file and:

```
[root@ibm-x3250m4-03 local-tmp-foreman]# semanage fcontext -l | grep puppet
/etc/puppet(/.*)?                                  all files          system_u:object_r:puppet_etc_t:s0 
/etc/puppetlabs(/.*)?                              all files          system_u:object_r:puppet_etc_t:s0
```

Out of curiousity, are you testing with EL 7.3? I know they were doing some huge SELinux rebase in this release.

**Comment by domcleal** [comment]
I'm using CentOS 7.2.1511, with selinux-policy-3.13.1-60.el7_2.3.noarch.

**Comment by lzap** [comment]
Disregard my comment, I just pushed and this works for me.

**Comment by domcleal** [comment]
Merged, thanks @lzap.

**Pull request merged**
