### PR TITLE
Fixes #13041 - passenger var context fix

### PR DESCRIPTION
**Pull request by lzap**
If this is confirmed to work, I will go ahead and fix this upstream:

https://github.com/TresysTechnology/refpolicy-contrib/blob/master/passenger.fc

Change in Passenger 4.0 perhaps?

### CODE REVIEW

**Comment by domcleal** [comment]
It's a patch in our package (https://github.com/theforeman/foreman-packaging/commit/a66b367702e9d0ee2b8e90dec8a8269153c4829d), which I think came from either Fedora or RHSCL packages.  The Fedora packages have since repackaged Passenger just as 'passenger' rather than 'rubygem-passenger', and now use /run/passenger again - so the patch is probably just needed here.

**Comment by domcleal** [comment]
Looks fine, but could you also update the relabel script to ensure it fixes it on installation please?

<pre>
# ll -dZ /var/run/*passenger/                                                                                         
drwxr-xr-x. root root system_u:object_r:var_run_t:s0   /var/run/rubygem-passenger/
# rpm -Uvh ...
# ll -dZ /var/run/*passenger/                                                                                         
drwxr-xr-x. root root system_u:object_r:var_run_t:s0   /var/run/rubygem-passenger/
# restorecon -Rvvn /var/run/*passenger/
restorecon reset /var/run/rubygem-passenger context system_u:object_r:var_run_t:s0->system_u:object_r:passenger_var_run_t:s0
</pre>

**Comment by lzap** [comment]
Good catch, added.

**Comment by lzap** [comment]
If you have a minute or two, I'd love to get this in plus I found one issue I will be filing in a sec.

**Comment by domcleal** [comment]
Merged as 86fa6e7, thanks @lzap.

**Pull request closed without merging**
