### PR TITLE
Update compilation GH action

### PR DESCRIPTION
**Pull request by lzap**
Use containers to build the policy, which is closer to our environment. I had no indea this could be done, container in a container?

### CODE REVIEW

**Comment by ekohl** [comment]
> I had no indea this could be done, container in a container?

My understanding is that it loads the specified container instead of some other container.

**Comment by lzap** [comment]
> My understanding is that it loads the specified container instead of some other container.

Interesting, they only list Ubuntu, Windows and Mac in their docs. I will use CentOS from now on for all my tasks.

**Comment by lzap** [comment]
Nice it works! Great. I've added check for shell syntax of all scripts. Mind taking a look @ekohl ?

**Comment by ekohl** [comment]
> Interesting, they only list Ubuntu, Windows and Mac in their docs. I will use CentOS from now on for all my tasks.

Note you can't use other actions such as python or ruby versions with such a container. Since it's a container you also won't have the kernel.

**Review by ekohl — APPROVED** [review]

**Comment by lzap** [comment]
> won't have the kernel

Well, you have one. Obviously. Running in a namespace tho. :-) Thanks.

**Comment by ekohl** [comment]
Fair enough. Not the matching kernel ;)

**Pull request merged**
