### PR TITLE
Fixes #7719 - added ssh rules for libvirt CR

### PR DESCRIPTION
**Pull request by lzap**

### CODE REVIEW

**Comment by lzap** [comment]
I noticed during reproducing this bug that I have the denials in my audit log, but Foreman does work without it for me. It relly looks like my box was in `Permissive` but it was not. User reports that Foreman was prevented in his case.

This patch allows the execution. Also, I want to create two patches for foreman and foreman-packaging to deploy the `/usr/share/foreman/.ssh` directory so it is properly labeled in all instalations so users will not struggle with ssh setup anymore. Please test thanks.

**Comment by lzap** [comment]
Ok here is the patch: https://github.com/theforeman/foreman/pull/1842

**Comment by lzap** [comment]
Packaging done, tested on RHEL6. Ready for review :-)

**Comment by domcleal** [comment]
Should this be inside a boolean, like with OpenStack?

**Comment by lzap** [comment]
You mean the whole libvirt-ssh part?

**Comment by lzap** [comment]
Note that I've added couple of new rules which were preventing the console to start.

**Comment by lzap** [comment]
I introduced a boolean. If you insist, I can create new PR with the console fix, which seemed to be one issue. Or we can merge it together.

**Comment by lzap** [comment]
Ok its now split into two commits, I think this is reasonable, what you think? Got a min to test all my selinux pull requests? ;-)

**Comment by domcleal** [comment]
Merged as b696bcf, 9fb8417 for Foreman 1.6.3.  Thanks @lzap!

**Pull request closed without merging**
