### PR TITLE
fixes #5930 - fix katello-jobs domain

### PR DESCRIPTION
**Pull request by lzap**
Fix for my previous commit, katello has an extra wrapper for foreman tasks.

https://bugzilla.redhat.com/show_bug.cgi?id=1084919

@domcleal - can I ask you for quick merge to hit the next snap? ty

### CODE REVIEW

**Comment by domcleal** [comment]
Do you have a link to the wrapper?  I can't see it.

**Comment by lzap** [comment]
https://github.com/Katello/katello/blob/master/deploy/script/katello-jobs

**Comment by lzap** [comment]
Ping? Any blockers here?

**Comment by mccun934** [comment]
looks good to me, ACK

**Comment by lzap** [comment]
Dom I am pulling this in, we will need to break katello and foreman selinux packages later on anyway. We need this context.

**Pull request merged**
