### PR TITLE
Fixes #34726 - Make git template sync work on EL8

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by ekohl** [comment]
EL8 in CI fails and I opened https://github.com/theforeman/foreman-selinux/pull/133 a while back, but never got around to completing it. Sadly I think it's particularly important now to see it does compile.

**Comment by evgeni** [comment]
Would you mind adding a test to https://github.com/theforeman/forklift/blob/master/bats/fb-test-foreman-templates.bats?

**Comment by adamruzicka** [comment]
> Would you mind adding a test to https://github.com/theforeman/forklift/blob/master/bats/fb-test-foreman-templates.bats?

https://github.com/theforeman/forklift/pull/1484

**Comment by ekohl** [comment]
Please rebase and CI should be green.

**Review by ekohl — APPROVED** [review]

**Review by evgeni — APPROVED** [review]

**Comment by adamruzicka** [comment]
CPs:
- 3.2 https://github.com/theforeman/foreman-selinux/pull/139
- 3.1 https://github.com/theforeman/foreman-selinux/pull/140

**Pull request merged**
