### PR TITLE
Fixes #7178 - allowed passenger_t to execmem

### PR DESCRIPTION
**Pull request by lzap**
Tested, see the ticket.

### CODE REVIEW

**Comment by lzap** [comment]
Ok I am merging this right away, it's the dynflow/foreman-tasks who does it. We need to solve this AFTER we split our policy into two (or more) domains. Until then, we need this rule to have this work on RHEL7. Let's discuss this afterwards.

**Comment by domcleal** [comment]
Please do not merge your own PRs without review (esp with merge commits), this had only been open for five hours - you know the review process, don't bypass it.

**Comment by lzap** [comment]
Yeah, sorry. I tried to fix late-night drop issue and we found another issue. I will provide more details here or in upcoming PR. Investigating.

**Comment by iNecas** [comment]
I've opened a PR for Katello to not require less-rails in production runtime, so that we would not need this anymore https://github.com/Katello/katello/pull/4673

**Comment by lzap** [comment]
Thanks, I will raise revert commit once it is merged.

**Pull request merged**
